package exámen02;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class InstitutoTrujillo extends javax.swing.JFrame {

    private Object código;
    private String ApellidoPaterno;
    private String ApellidoMaterno;
    private String PrimerNombre;
    private String SegundoNombre;
    private String CarreraProfesional;
    private int módulo;
    private char turno;
    private String FechaNacimiento;

    private static boolean CódigoGenerado;
    private static boolean DatosGuardados;

    Estudiante estudiante = new Estudiante();

    public InstitutoTrujillo() {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(974, 654);

        //Obtenemos la fecha y hora actual del sistema
        DateTimeFormatter FormatoFecha = DateTimeFormatter.ofPattern("dd/LL/yyyy");
        DateTimeFormatter FormatoHora = DateTimeFormatter.ofPattern("hh:mm:ss");

        LocalDate FechaActual = LocalDate.now();
        LocalTime HoraActual = LocalTime.now();

        //Estas acciones se ejecutan antes de que el usuario ingrese valores en el formulario
        txtFecha.setText(FormatoFecha.format(FechaActual));
        txtHora.setText(FormatoHora.format(HoraActual));
        txtFechaNacimiento.setText("00/00/0000");
        //FechaNacimiento = txtFechaNacimiento.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTurno = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnTítulo = new javax.swing.JTextPane();
        txtPagoCarrera = new javax.swing.JTextField();
        txtDescuentoTurno = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRecogerFicha = new javax.swing.JTextField();
        txtQueCorresponde = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCódigo = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        cmbCarreraProfesional = new javax.swing.JComboBox<>();
        cmbMódulo = new javax.swing.JComboBox<>();
        rbtnNocturno = new javax.swing.JRadioButton();
        rbtnVespertino = new javax.swing.JRadioButton();
        rbtnDiurno = new javax.swing.JRadioButton();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGenerarCódigo = new javax.swing.JButton();
        btnGuardarDatos = new javax.swing.JButton();
        btnCalcularEdad = new javax.swing.JButton();
        btnPagosMatrícula = new javax.swing.JButton();
        btnFichaMatrícula = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnTurno = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 50));

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel3.setText("Hora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 110, -1));

        txtHora.setEditable(false);
        txtHora.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 110, -1));

        pnTítulo.setEditable(false);
        pnTítulo.setBackground(new java.awt.Color(226, 112, 234));
        pnTítulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(pnTítulo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 910, 85));

        txtPagoCarrera.setEditable(false);
        getContentPane().add(txtPagoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 160, -1));

        txtDescuentoTurno.setEditable(false);
        getContentPane().add(txtDescuentoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 160, -1));

        txtTotalPagar.setEditable(false);
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 160, -1));

        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("Pagos de Matrícula en S/.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel15.setForeground(new java.awt.Color(153, 0, 153));
        jLabel15.setText("==> Pago por Carrera Profesional");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("==> Descuento por Turno");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("==> Total a Pagar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("Entrega de Fícha de Matrícula");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        jLabel17.setForeground(new java.awt.Color(153, 0, 153));
        jLabel17.setText("Recoger la ficha dentro de 15 días, exactamente el ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        txtRecogerFicha.setEditable(false);
        getContentPane().add(txtRecogerFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 200, -1));

        txtQueCorresponde.setEditable(false);
        getContentPane().add(txtQueCorresponde, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 140, -1));

        jLabel18.setForeground(new java.awt.Color(153, 0, 153));
        jLabel18.setText("Que corresponde a un día");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        txtEdad.setEditable(false);
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 80, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Edad (años)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Carrera Profesional");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Módulo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Segundo Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtCódigo.setEditable(false);
        getContentPane().add(txtCódigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 140, -1));
        getContentPane().add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, -1));
        getContentPane().add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, -1));
        getContentPane().add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, -1));
        getContentPane().add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, -1));

        cmbCarreraProfesional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPUTACIÓN E INFORMÁTICA", "CONTABILIDAD", "ENFERMERÍA TÉCNICA", "GUIA OFICIAL DE TURISMO", "LABORATORIO CLÍNICO", "SECRETARIADO EJECUTIVO", "RELACIONES PÚBLICAS" }));
        getContentPane().add(cmbCarreraProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 220, -1));

        cmbMódulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(cmbMódulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        rbtnNocturno.setBackground(new java.awt.Color(255, 255, 255));
        btngTurno.add(rbtnNocturno);
        rbtnNocturno.setText("Nocturno");
        getContentPane().add(rbtnNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        rbtnVespertino.setBackground(new java.awt.Color(255, 255, 255));
        btngTurno.add(rbtnVespertino);
        rbtnVespertino.setText("Vespertino");
        getContentPane().add(rbtnVespertino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        rbtnDiurno.setBackground(new java.awt.Color(255, 255, 255));
        btngTurno.add(rbtnDiurno);
        rbtnDiurno.setText("Diurno");
        getContentPane().add(rbtnDiurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 120, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Apellido Materno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Apellido Paterno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Código");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Primer Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btnNuevo.setText("N");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, 40));

        btnGenerarCódigo.setText("GC");
        btnGenerarCódigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCódigoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarCódigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, 40));

        btnGuardarDatos.setText("GD");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, 40));

        btnCalcularEdad.setText("CE");
        btnCalcularEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEdadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, 40));

        btnPagosMatrícula.setText("PM");
        btnPagosMatrícula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosMatrículaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagosMatrícula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, 40));

        btnFichaMatrícula.setText("FM");
        btnFichaMatrícula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaMatrículaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFichaMatrícula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, 40));

        btnSalir.setText("S");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, -1, 40));

        pnTurno.setEditable(false);
        pnTurno.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane3.setViewportView(pnTurno);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 445, 320, 40));

        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Turno");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jTextPane3.setEditable(false);
        jScrollPane2.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 390, 450));

        jTextPane4.setEditable(false);
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 510, 150));

        jTextPane5.setEditable(false);
        jScrollPane5.setViewportView(jTextPane5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 510, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Volvemos a su estado inicial a todos los componentes y reiniciamos las variables booleanas
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtApellidoMaterno.setText("");
        txtApellidoPaterno.setText("");
        txtCódigo.setText("");
        txtDescuentoTurno.setText("");
        txtEdad.setText("");
        txtFechaNacimiento.setText("00/00/0000");
        txtPagoCarrera.setText("");
        txtPrimerNombre.setText("");
        txtQueCorresponde.setText("");
        txtRecogerFicha.setText("");
        txtSegundoNombre.setText("");
        txtTotalPagar.setText("");
        cmbCarreraProfesional.setSelectedIndex(0);
        cmbMódulo.setSelectedIndex(0);
        btngTurno.clearSelection();
        rbtnDiurno.setSelected(false);
        rbtnVespertino.setSelected(false);
        rbtnNocturno.setSelected(false);

        txtApellidoMaterno.setBackground(new Color(255, 255, 255));
        txtApellidoPaterno.setBackground(new Color(255, 255, 255));
        txtPrimerNombre.setBackground(new Color(255, 255, 255));
        txtSegundoNombre.setBackground(new Color(255, 255, 255));
        txtCódigo.setBackground(new Color(255, 255, 255));
        txtFechaNacimiento.setBackground(new Color(255, 255, 255));

        CódigoGenerado = false;
        DatosGuardados = false;
    }//GEN-LAST:event_btnNuevoActionPerformed

    /*Validos que el usuario ingrese su turno y fecha de nacimiento para generar el código, luego activamos la 
    variable CódigoGenerado*/
    private void btnGenerarCódigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCódigoActionPerformed

        int validación = 0;
        FechaNacimiento = txtFechaNacimiento.getText().trim();

        if (FechaNacimiento.equals("")) {
            txtFechaNacimiento.setBackground(new Color(226, 112, 234));
            validación += 1;
            JOptionPane.showMessageDialog(null, "Debes ingresar tu fecha de nacimiento");
        }

        if (rbtnDiurno.isSelected() == false && rbtnVespertino.isSelected() == false && rbtnNocturno.isSelected() == false) {
            validación += 1;
            JOptionPane.showMessageDialog(null, "Debes seleccionar tu turno");
        }

        if (validación == 0) {

            CarreraProfesional = cmbCarreraProfesional.getSelectedItem().toString();
            módulo = cmbMódulo.getSelectedIndex() + 1;

            if (rbtnDiurno.isSelected()) {
                turno = 'D';
            } else if (rbtnVespertino.isSelected()) {
                turno = 'V';
            } else if (rbtnNocturno.isSelected()) {
                turno = 'N';
            }

            int día = Integer.parseInt(FechaNacimiento.substring(0, 2));
            String CadenaDía;

            if (día >= 1 && día <= 9) {
                CadenaDía = "0" + día;
                código = CarreraProfesional.substring(0, 2) + módulo + turno + CadenaDía;
                txtCódigo.setText(String.valueOf(código));
                CódigoGenerado = true;

            } else if (día >= 10 && día <= 31) {
                CadenaDía = "" + día;
                código = CarreraProfesional.substring(0, 2) + módulo + turno + CadenaDía;
                txtCódigo.setText(String.valueOf(código));
                CódigoGenerado = true;

            } else {
                JOptionPane.showMessageDialog(null, "ERROR en la fecha de nacimiento");
            }
        }
    }//GEN-LAST:event_btnGenerarCódigoActionPerformed

    /*Validamos que el usuario haya generado su código e ingresado sus nombres y apellidos completos, luego guardamos 
    todos los datos en la clase Estudiante*/
    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed

        int validación = 0;

        if (CódigoGenerado == true) {

            ApellidoPaterno = txtApellidoPaterno.getText().trim();
            ApellidoMaterno = txtApellidoMaterno.getText().trim();
            PrimerNombre = txtPrimerNombre.getText().trim();
            SegundoNombre = txtSegundoNombre.getText().trim();

            if (ApellidoMaterno.equals("")) {
                txtApellidoMaterno.setBackground(new Color(226, 112, 234));
                validación += 1;
            }

            if (ApellidoPaterno.equals("")) {
                txtApellidoPaterno.setBackground(new Color(226, 112, 234));
                validación += 1;
            }

            if (PrimerNombre.equals("")) {
                txtPrimerNombre.setBackground(new Color(226, 112, 234));
                validación += 1;
            }

            if (SegundoNombre.equals("")) {
                txtSegundoNombre.setBackground(new Color(226, 112, 234));
                validación += 1;
            }

            if (validación == 0) {

                estudiante.GuardarDatos(código, ApellidoPaterno, ApellidoMaterno, PrimerNombre, SegundoNombre,
                        CarreraProfesional, módulo, turno, FechaNacimiento);
                DatosGuardados = true;

                txtApellidoMaterno.setBackground(new Color(255, 255, 255));
                txtApellidoPaterno.setBackground(new Color(255, 255, 255));
                txtPrimerNombre.setBackground(new Color(255, 255, 255));
                txtSegundoNombre.setBackground(new Color(255, 255, 255));
                txtCódigo.setBackground(new Color(255, 255, 255));
                txtFechaNacimiento.setBackground(new Color(255, 255, 255));
                cmbCarreraProfesional.setBackground(new Color(255, 255, 255));
                cmbMódulo.setBackground(new Color(255, 255, 255));

            } else {
                JOptionPane.showMessageDialog(null, "Debes ingresar tus apellidos y nombres completos");
            }

        } else {
            txtCódigo.setBackground(new Color(226, 112, 234));
            JOptionPane.showMessageDialog(null, "Debes generar el código");
        }
    }//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnCalcularEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEdadActionPerformed

        if (DatosGuardados == true) {
            estudiante.CalcularEdad();
            txtEdad.setText(String.valueOf(estudiante.CalcularEdad()));

        } else {
            JOptionPane.showMessageDialog(null, "Debes guardar los datos");
        }
    }//GEN-LAST:event_btnCalcularEdadActionPerformed

    private void btnPagosMatrículaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosMatrículaActionPerformed

        if (DatosGuardados == true) {
            txtPagoCarrera.setText(String.valueOf(estudiante.PagoCarrera()));
            txtDescuentoTurno.setText(String.valueOf(estudiante.DescuentoTurno()));
            txtTotalPagar.setText(String.valueOf(estudiante.TotalPagar()));

        } else {
            JOptionPane.showMessageDialog(null, "Debes guardar los datos");
        }
    }//GEN-LAST:event_btnPagosMatrículaActionPerformed

    //Determinamos la fecha de recojo de la ficha de matrícula y el nombre del día correspondiente
    private void btnFichaMatrículaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaMatrículaActionPerformed

        if (DatosGuardados == true) {

            Calendar calendario = Calendar.getInstance();

            int DíaMesRecojo = calendario.get(Calendar.DATE) + 15;
            int DíaSemanaRecojo = calendario.get(Calendar.DAY_OF_WEEK) + 1;
            String Cadena_DíaSemanaRecojo = "";
            int CantidadDías = 0;
            int MesRecojo = calendario.get(Calendar.MONTH);
            String Cadena_MesRecojo = "";
            int annio = calendario.get(Calendar.YEAR);

            switch (MesRecojo) {
                case 0:
                case 2:
                case 4:
                case 6:
                case 7:
                case 9:
                case 11:
                    CantidadDías = 31;
                    break;

                case 3:
                case 5:
                case 8:
                case 10:
                    CantidadDías = 30;
                    break;

                case 1:
                    if (annio % 4 == 0) {
                        CantidadDías = 29;
                    } else {
                        CantidadDías = 28;
                    }
                    break;
            }

            if (DíaMesRecojo > CantidadDías) {
                DíaMesRecojo = DíaMesRecojo - CantidadDías;
                MesRecojo += 1;
            }

            if (DíaSemanaRecojo == 8) {
                DíaSemanaRecojo = 1;
            }

            switch (MesRecojo) {
                case 0:
                    Cadena_MesRecojo = "Enero";
                    break;
                case 1:
                    Cadena_MesRecojo = "Febrero";
                    break;
                case 2:
                    Cadena_MesRecojo = "Marzo";
                    break;
                case 3:
                    Cadena_MesRecojo = "Abril";
                    break;
                case 4:
                    Cadena_MesRecojo = "Mayo";
                    break;
                case 5:
                    Cadena_MesRecojo = "Junio";
                    break;
                case 6:
                    Cadena_MesRecojo = "Julio";
                    break;
                case 7:
                    Cadena_MesRecojo = "Agosto";
                    break;
                case 8:
                    Cadena_MesRecojo = "Septiembre";
                    break;
                case 9:
                    Cadena_MesRecojo = "Octubre";
                    break;
                case 10:
                    Cadena_MesRecojo = "Noviembre";
                    break;
                case 11:
                    Cadena_MesRecojo = "Diciembre";
                    break;
            }

            switch (DíaSemanaRecojo) {
                case 1:
                    Cadena_DíaSemanaRecojo = "Domingo";
                    break;
                case 2:
                    Cadena_DíaSemanaRecojo = "Lunes";
                    break;
                case 3:
                    Cadena_DíaSemanaRecojo = "Martes";
                    break;
                case 4:
                    Cadena_DíaSemanaRecojo = "Miércoles";
                    break;
                case 5:
                    Cadena_DíaSemanaRecojo = "Jueves";
                    break;
                case 6:
                    Cadena_DíaSemanaRecojo = "Viernes";
                    break;
                case 7:
                    Cadena_DíaSemanaRecojo = "Sábado";
                    break;
            }

            txtRecogerFicha.setText(DíaMesRecojo + " de " + Cadena_MesRecojo + " del " + annio);
            txtQueCorresponde.setText(Cadena_DíaSemanaRecojo);

        } else {
            JOptionPane.showMessageDialog(null, "Debes guardar los datos");
        }
    }//GEN-LAST:event_btnFichaMatrículaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstitutoTrujillo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstitutoTrujillo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstitutoTrujillo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstitutoTrujillo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstitutoTrujillo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularEdad;
    private javax.swing.JButton btnFichaMatrícula;
    private javax.swing.JButton btnGenerarCódigo;
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPagosMatrícula;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup btngTurno;
    private javax.swing.JComboBox<String> cmbCarreraProfesional;
    private javax.swing.JComboBox<String> cmbMódulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane pnTurno;
    private javax.swing.JTextPane pnTítulo;
    private javax.swing.JRadioButton rbtnDiurno;
    private javax.swing.JRadioButton rbtnNocturno;
    private javax.swing.JRadioButton rbtnVespertino;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCódigo;
    private javax.swing.JTextField txtDescuentoTurno;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtPagoCarrera;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtQueCorresponde;
    private javax.swing.JTextField txtRecogerFicha;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
