package exámen01;

public class Librería_ElGranLibro extends javax.swing.JFrame {

    public Librería_ElGranLibro() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(675, 574);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoClientes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rbtnClienteNormal = new javax.swing.JRadioButton();
        rbtnClientePreferencial = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTotalPagar = new javax.swing.JButton();
        cmbMateriaLibro = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        cmbCantidad = new javax.swing.JComboBox<>();
        txtImporteVentas = new javax.swing.JTextField();
        txtIGV = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CLIENTE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 270, -1));

        btngTipoClientes.add(rbtnClienteNormal);
        rbtnClienteNormal.setText("CLIENTE NORMAL");
        getContentPane().add(rbtnClienteNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        btngTipoClientes.add(rbtnClientePreferencial);
        rbtnClientePreferencial.setText("CLIENTE PREFERENCIAL");
        getContentPane().add(rbtnClientePreferencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel2.setText("NOMBRE DEL LIBRO --->");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel3.setText("PRECIO UNITARIO S/. --->");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel4.setText("CANTIDAD --->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel5.setText("IMPORTE VENTAS S/. --->");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel6.setText("IGV (18%) S/. --->");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));
        getContentPane().add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel8.setText("TOTAL A PAGAR S/. --->");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        btnTotalPagar.setText("TOTAL A PAGAR");
        btnTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        cmbMateriaLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LENGUAJE", "LITERATURA", "HISTORIA", "GEOGRAFIA", "BIOLOGÍA", "CIENCIA Y AMBIENTE", "OTRAS MATERIAS" }));
        getContentPane().add(cmbMateriaLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel9.setText("LIBRERÍA \"EL GRAN LIBRO\"");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));
        getContentPane().add(txtPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 80, -1));

        cmbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        txtImporteVentas.setEnabled(false);
        getContentPane().add(txtImporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 100, -1));

        txtIGV.setEnabled(false);
        getContentPane().add(txtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, -1));

        txtDescuento.setEnabled(false);
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, -1));

        txtTotalPagar.setEnabled(false);
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 100, -1));

        jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturación:"));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 540, 350));

        jLabel10.setText("TIPO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 105, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPagarActionPerformed
        float precio, ImporteVentas, igv, descuento = 0, TotalPagar;
        int cantidad;
        String TipoCliente = "", MateriaLibro;

        precio = Float.parseFloat(txtPrecioUnitario.getText());
        cantidad = Integer.parseInt(cmbCantidad.getSelectedItem().toString());
        MateriaLibro = cmbMateriaLibro.getSelectedItem().toString();

        //Calculamos Importe de ventas
        ImporteVentas = precio * cantidad;
        txtImporteVentas.setText(String.valueOf(ImporteVentas));

        //Calculamos el IGV
        igv = ImporteVentas * 18 / 100;
        txtIGV.setText(String.valueOf(igv));
        
        //Determinamos el tipo de cliente
        if (rbtnClienteNormal.isSelected() == true) {
            TipoCliente = "NORMAL";
        }
        if (rbtnClientePreferencial.isSelected() == true) {
            TipoCliente = "PREFERENCIAL";
        }

        //Si es cliente preferencial determinamos su descuento según la materia del libro adquirido
        if (TipoCliente.equals("NORMAL")) {
            txtDescuento.setText("0");
        } else if (TipoCliente.equals("PREFERENCIAL")) {

            switch (MateriaLibro) {
                case "LENGUAJE":
                    descuento = ImporteVentas * 20 / 100;
                    lblDescuento.setText("DESCUENTO (20%) S/. --->");                    
                    break;
                case "LITERATURA":
                    descuento = ImporteVentas * 10 / 100;
                    lblDescuento.setText("DESCUENTO (10%) S/. --->");  
                    break;
                case "HISTORIA":
                    descuento = ImporteVentas * 30 / 100;
                    lblDescuento.setText("DESCUENTO (30%) S/. --->"); 
                    break;
                case "GEOGRAFÍA":
                    descuento = ImporteVentas * 30 / 100;
                    lblDescuento.setText("DESCUENTO (30%) S/. --->"); 
                    break;
                case "BIOLOGÍA":
                    descuento = ImporteVentas * 20 / 100;
                    lblDescuento.setText("DESCUENTO (20%) S/. --->"); 
                    break;
                case "CIENCIA Y AMBIENTE":
                    descuento = ImporteVentas * 15 / 100;
                    lblDescuento.setText("DESCUENTO (15%) S/. --->"); 
                    break;
                case "OTRAS MATERIAS":
                    descuento = 0;
                    lblDescuento.setText("DESCUENTO (0%) S/. --->"); 
                    break;
            }
            txtDescuento.setText(String.valueOf(descuento));
        }
        
        //Calculamos el total a pagar
        TotalPagar = ImporteVentas - descuento;
        txtTotalPagar.setText(String.valueOf(TotalPagar));
    }//GEN-LAST:event_btnTotalPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librería_ElGranLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librería_ElGranLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librería_ElGranLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librería_ElGranLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librería_ElGranLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTotalPagar;
    private javax.swing.ButtonGroup btngTipoClientes;
    private javax.swing.JComboBox<String> cmbCantidad;
    private javax.swing.JComboBox<String> cmbMateriaLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JRadioButton rbtnClienteNormal;
    private javax.swing.JRadioButton rbtnClientePreferencial;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtImporteVentas;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
